name: Username print Workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'First name'
        required: true
        default: 'user'
        type: string
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello ${{ github.event.inputs.name }}!"
      - name: Print goodbye
        run: echo "Done - bye!"
