name: second workflow
on:
    workflow_dispatch:
        inputs:
            name: 
                description: "Do you want to run it now?"
                required: true
                default: "yes"
                options:
                    - yes
                    - no
                type: choice
jobs:
    
    push-job:
        if : ${{github.event.inputs.name == 'yes'}}
        runs-on: ubuntu-latest
        steps:
            - name : Print a message
              run: echo "This is the second workflow"
            
            - name: Sleep for 15 seconds
              run: sleep 20s
              shell: bash
            
            - name: Print another message
              run: echo "This is another message"