name: second workflow
on:
   push:
    branches: [main]

jobs:
  end-to-end:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Install Node.Js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test

      - name: Deploy to Azure
        run: echo "Deploying to Azure Webapp"
        
      - name: sleep
        run: sleep 10



